In [3]:
import pandas as pd
data = {
    "Name":["Amit","Riya","Vishal","Yash","Priya"],
    "Age":[20,21,20,22,21],
    "Department":["CSE","IT","CSE","ECE","IT"],
    "Marks":[85,90,78,88,76]
}
df=pd.DataFrame(data)
print(df)

     Name  Age Department  Marks
0    Amit   20        CSE     85
1    Riya   21         IT     90
2  Vishal   20        CSE     78
3    Yash   22        ECE     88
4   Priya   21         IT     76

In [4]:
print(df.head())
print(df.head())
print("Shape:" , df.shape)
print(df.info())
print(df.describe)

     Name  Age Department  Marks
0    Amit   20        CSE     85
1    Riya   21         IT     90
2  Vishal   20        CSE     78
3    Yash   22        ECE     88
4   Priya   21         IT     76
     Name  Age Department  Marks
0    Amit   20        CSE     85
1    Riya   21         IT     90
2  Vishal   20        CSE     78
3    Yash   22        ECE     88
4   Priya   21         IT     76
Shape: (5, 4)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      object
 1   Age         5 non-null      int64
 2   Department  5 non-null      object
 3   Marks       5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes
None
<bound method NDFrame.describe of      Name  Age Department  Marks
0    Amit   20        CSE     85
1    Riya   21         IT     90
2  Vishal   20        CSE     78
3    Yash   22        ECE     88
4   Priya   21         IT     76>

In [11]:
df.to_csv("Students.csv",index=False)

In [1]:
import pandas as pd
iris_df = pd.read_csv('/content/iris.csv')

In [2]:
print(iris_df.head())
print(iris_df.tail())
print(iris_df.describe())
print(iris_df.info())
print(iris_df.shape)
print(iris_df.columns)
print(iris_df.dtypes)
print(iris_df.isnull().sum())
print(iris_df.duplicated().sum())
print(iris_df.drop_duplicates(inplace=True))
print(iris_df.shape)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
     sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica
       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
None
(150, 5)
Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')
sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object
sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64
3
None
(147, 5)

#Save and Load Excel

In [6]:
iris_df.to_excel('iris_output.xlsx', index=False)

In [9]:
iris_excel=pd.read_excel("iris_output.xlsx")
iris_excel.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

#Save and Load JSON

In [19]:
import pandas as pd
iris_df.to_json("iris_output.json",orient="records",indent=4)

In [23]:
iris_json = pd.read_json("/content/iris_output.json")
iris_json.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

#Created/Dowlode a data
#dowlode from kaggle
#load the data
# Pandas DataFrame
#inspection/preprocessing

#store the data in different formates:
##CSV
 =>read_csv()
 =>to_csv()
##EXCEL
 =>read_excel()
 =>to_excel()
##JSON
 =>read_json()
 =>to_json()

#Compare Files Sizes

In [24]:

import os
files=["Students.csv","iris_output.xlsx","iris_output.json"]
for file in files:
  size=os.path.getsize(file)
  print(f"{file} : {size} bytes")

Students.csv : 102 bytes
iris_output.xlsx : 8349 bytes
iris_output.json : 22399 bytes

#Loading only Selected Columns

In [29]:
iris_sel=pd.read_csv("iris.csv",usecols=["sepal_length","sepal_width"])
iris_sel.head()

   sepal_length  sepal_width
0           5.1          3.5
1           4.9          3.0
2           4.7          3.2
3           4.6          3.1
4           5.0          3.6

#Loading a Limited Number of Rows

In [26]:
sample=pd.read_csv("iris.csv",nrows=10)
sample.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

#Filtering Data

In [31]:
result = iris_df[iris_df["sepal_length"]>6]
result.head()

    sepal_length  sepal_width  petal_length  petal_width     species
50           7.0          3.2           4.7          1.4  versicolor
51           6.4          3.2           4.5          1.5  versicolor
52           6.9          3.1           4.9          1.5  versicolor
54           6.5          2.8           4.6          1.5  versicolor
56           6.3          3.3           4.7          1.6  versicolor